version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - broker-kafka
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: "/tmp/logs"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    networks:
      - broker-kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      LOG_DIR: "/tmp/logs"

  consumer:
    image: streaming-dmn-kafka-consumer:1.0
    depends_on:
      - kafka
    networks:
      - broker-kafka
    ports:
      - "8090:8080"
    build:
      context: streaming-dmn-kafka-consumer
      dockerfile: src/main/docker/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  producer_a:
    image: streaming-dmn-kafka-producer:1.0
    depends_on:
      - consumer
    networks:
      - broker-kafka
    ports:
      - "8080:8080"
    build:
      context: streaming-dmn-kafka-producer
      dockerfile: src/main/docker/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PRODUCER_NAME: A
      PRODUCER_FREQUENCY: 5

  producer_b:
    image: streaming-dmn-kafka-producer:1.0
    depends_on:
      - consumer
    networks:
      - broker-kafka
    ports:
      - "8081:8080"
    build:
      context: streaming-dmn-kafka-producer
      dockerfile: src/main/docker/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PRODUCER_NAME: B
      PRODUCER_FREQUENCY: 10

  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    networks:
      - broker-kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9093"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"

networks:
  broker-kafka:
    name: ks
